CREATE DATABASE IF NOT EXISTS scholarhub CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE scholarhub;

CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,role ENUM('student','admin') NOT NULL DEFAULT 'student',target_country VARCHAR(100) NULL,study_level VARCHAR(80) NULL,field VARCHAR(150) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS scholarships (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL UNIQUE,provider VARCHAR(255) NOT NULL,country VARCHAR(100) NOT NULL,study_level VARCHAR(150) NULL,fields TEXT NULL,funding_type VARCHAR(100) NULL,official_url TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS universities (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,country VARCHAR(100) NOT NULL,city VARCHAR(100) NULL,description TEXT NULL,official_url TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS fields (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL UNIQUE,description TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

INSERT INTO users(name,email,password,role) SELECT 'ScholarHub Admin','admin@scholarhub.local','$2y$12$xBp4TzSNjFHvL9OxXr5yuu7qwiwePtpEnNOuhvZrz/yjgWOlvMkHy','admin' WHERE NOT EXISTS (SELECT 1 FROM users WHERE email='admin@scholarhub.local');

INSERT INTO scholarships(title,provider,country,study_level,fields,funding_type,official_url) VALUES
('MEXT Scholarship','MEXT','Japan','Undergraduate; Master''s; PhD; Research','Multiple Fields','','https://www.mext.go.jp/en/policy/education/highered/title02/detail02/1373897.htm'),
('Chevening Scholarship','Chevening / FCDO','United Kingdom','Master''s','Multiple Fields','','https://www.chevening.org/scholarships/'),
('Commonwealth Master''s Scholarship','Commonwealth Scholarship Commission','United Kingdom','Master''s','Program-specific / Development themes','','https://cscuk.fcdo.gov.uk/scholarships/'),
('Commonwealth PhD Scholarship','Commonwealth Scholarship Commission','United Kingdom','PhD','Program-specific / Development themes','','https://cscuk.fcdo.gov.uk/scholarships/commonwealth-phd-scholarships/'),
('Erasmus Mundus Joint Masters','European Commission / Erasmus+','Europe','Master''s','Program-specific / Multiple Fields','','https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters'),
('Fulbright Foreign Student Program','Fulbright / U.S. Department of State','United States','Master''s; PhD; Research','Multiple Fields','','https://foreign.fulbrightonline.org/about/foreign-student-program'),
('DAAD Scholarships','DAAD','Germany','Master''s; PhD; Research','Multiple Fields / Program-specific','','https://www.daad.de/en/studying-in-germany/scholarships/'),
('Swiss Government Excellence Scholarships','Swiss Government / FCS','Switzerland','Research; PhD; Postdoctoral; Master''s (selected arts)','Program-specific / Multiple Fields','','https://www.swissuniversities.ch/en/topics/international-cooperation/scholarships'),
('Türkiye Scholarships','YTB','Türkiye','Undergraduate; Master''s; PhD; Research','Multiple Fields','','https://www.turkiyeburslari.gov.tr/scholarshipsprograms'),
('Stipendium Hungaricum','Tempus Public Foundation / Government of Hungary','Hungary','Undergraduate; Master''s; PhD; Exchange','Multiple Fields / Program-specific','','https://stipendiumhungaricum.hu/'),
('Chinese Government Scholarship (CSC)','China Scholarship Council','China','Undergraduate; Master''s; PhD; Research','Multiple Fields / Program-specific','','https://www.campuschina.org/'),
('Global Korea Scholarship (GKS)','NIIED','South Korea','Undergraduate; Master''s; PhD; Research','Multiple Fields / Program-specific','','https://www.studyinkorea.go.kr/'),
('Australia Awards Scholarships','Australian Government DFAT','Australia','Undergraduate; Master''s; Postgraduate','Program-specific / Priority areas','','https://www.dfat.gov.au/people-to-people/australia-awards/australia-awards-scholarships'),
('Manaaki New Zealand Scholarships','New Zealand Government / MFAT','New Zealand','Undergraduate; Master''s; PhD; Short Course','Program-specific / Development priorities','','https://www.nzscholarships.govt.nz/'),
('SI Scholarship for Global Professionals','Swedish Institute','Sweden','Master''s','Program-specific / Eligible SI fields','','https://si.se/en/apply/scholarships/'),
('France Excellence Eiffel Scholarship','French Ministry / Campus France','France','Master''s; PhD','Program-specific','','https://www.campusfrance.org/en/france-excellence-eiffel-scholarship-program'),
('Government of Ireland International Education Scholarship','Higher Education Authority','Ireland','Master''s; Postgraduate Diploma; PhD','Multiple Fields / Institution-specific','','https://hea.ie/policy/internationalisation/goi-ies/'),
('NL Scholarship','Dutch Ministry + participating universities','Netherlands','Undergraduate; Master''s','Multiple Fields / Institution-specific','','https://www.studyinnl.org/finances/nl-scholarship'),
('VLIR-UOS Scholarships','VLIR-UOS','Belgium','Master''s; Short Course','Program-specific / Development-related','','https://www.vliruos.be/en/scholarships'),
('ARES Scholarships','ARES','Belgium','Master''s; Advanced Bachelor''s; Training','Program-specific','','https://www.ares-ac.be/en/cooperation-au-developpement/bourses-et-mobilites'),
('JDS Scholarship','JDS / Government of Japan','Japan','Master''s; PhD','Program-specific / Public policy & development','','https://www.jds-scholarship.org/'),
('ADB-Japan Scholarship Program','Asian Development Bank / Japan','Asia-Pacific','Master''s','Program-specific / Development fields','','https://www.adb.org/work-with-us/careers/japan-scholarship-program'),
('Joint Japan/World Bank Graduate Scholarship','World Bank / Japan','Global','Master''s','Program-specific / Development-related','','https://www.worldbank.org/en/programs/scholarships/jj-wbgsp'),
('IsDB Scholarship Programs','Islamic Development Bank','Global / IsDB member countries','Undergraduate; Master''s; PhD; Postdoctoral; Research','Program-specific','','https://www.isdb.org/scholarships/scholarship-programs'),
('Hubert H. Humphrey Fellowship','U.S. Department of State','United States','Fellowship','Program-specific','','https://www.humphreyfellowship.org/'),
('AAUW International Fellowships','AAUW','United States','Master''s; PhD; Postdoctoral','Multiple Fields','','https://www.aauw.org/resources/programs/fellowships-grants/current-fellows/'),
('GREAT Scholarships','British Council + UK universities','United Kingdom','Master''s','Multiple Fields / University-specific','','https://study-uk.britishcouncil.org/scholarships-funding/great-scholarships'),
('Rotary Peace Fellowship','Rotary Foundation','Global','Master''s; Professional Development','Peace & Conflict / Related fields','','https://www.rotary.org/en/our-programs/peace-fellowships'),
('Oxford Clarendon Scholarship','University of Oxford','United Kingdom','Master''s; PhD','Multiple Fields','','https://www.ox.ac.uk/clarendon'),
('Rhodes Scholarship','Rhodes Trust / Oxford','United Kingdom','Master''s; PhD / Postgraduate','Multiple Fields','','https://www.rhodeshouse.ox.ac.uk/scholarships/'),
('Gates Cambridge Scholarship','Gates Cambridge / University of Cambridge','United Kingdom','Master''s; PhD','Multiple Fields','','https://www.gatescambridge.org/'),
('Cambridge Trust Scholarships','Cambridge Trust','United Kingdom','Undergraduate; Master''s; PhD','Multiple Fields','','https://www.cambridgetrust.org/'),
('Knight-Hennessy Scholars','Stanford University','United States','Graduate','Multiple Fields','','https://knight-hennessy.stanford.edu/'),
('Schwarzman Scholars','Tsinghua University / Schwarzman Scholars','China','Master''s','Global Affairs / Program-specific','','https://www.schwarzmanscholars.org/'),
('Yenching Academy Scholarship','Peking University / Yenching Academy','China','Master''s','China Studies / Interdisciplinary','','https://yenchingacademy.org/'),
('Vanier Canada Graduate Scholarships','Government of Canada','Canada','PhD','Health; Natural Sciences & Engineering; Social Sciences & Humanities','','https://vanier.gc.ca/en/home-accueil.html'),
('Lester B. Pearson International Scholarship','University of Toronto','Canada','Undergraduate','Multiple Fields','','https://future.utoronto.ca/pearson/'),
('McCall MacBain Scholarship','McGill University / McCall MacBain Foundation','Canada','Master''s; Professional','Multiple Fields / Eligible McGill programs','','https://mccallmacbainscholars.org/'),
('UBC International Scholars Program','University of British Columbia','Canada','Undergraduate','Multiple Fields / Eligible UBC programs','','https://you.ubc.ca/financial-planning/scholarships-awards-international-students/'),
('Mastercard Foundation Scholars at McGill','McGill / Mastercard Foundation','Canada','Undergraduate; Master''s','Program-specific','','https://www.mcgill.ca/mastercardfdn-scholars/'),
('Mastercard Foundation Scholars at Toronto','University of Toronto / Mastercard Foundation','Canada','Undergraduate; Master''s; PhD','Program-specific','','https://mastercardfdn.utoronto.ca/'),
('University of Edinburgh Global Scholarships','University of Edinburgh','United Kingdom','Master''s','Multiple Fields / Eligible programs','','https://www.ed.ac.uk/student-funding/postgraduate/international'),
('UCL Global Undergraduate Scholarship','University College London','United Kingdom','Undergraduate','Multiple Fields','','https://www.ucl.ac.uk/scholarships/ucl-global-undergraduate-scholarship'),
('Imperial President''s Undergraduate Scholarships','Imperial College London','United Kingdom','Undergraduate','Multiple Fields','','https://www.imperial.ac.uk/study/fees-and-funding/undergraduate-funding/'),
('LSE Graduate Support Scheme','London School of Economics','United Kingdom','Master''s','Multiple Fields / LSE programs','','https://www.lse.ac.uk/study-at-lse/Graduate/fees-and-funding'),
('Bristol Think Big Scholarships','University of Bristol','United Kingdom','Undergraduate; Master''s','Multiple Fields','','https://www.bristol.ac.uk/students/fees-funding/scholarships/'),
('Warwick Chancellor''s International Scholarships','University of Warwick','United Kingdom','PhD','Multiple Fields','','https://warwick.ac.uk/services/dc/schols_fund/scholarships/chancellors/'),
('Manchester Global Futures Scholarship','University of Manchester','United Kingdom','Undergraduate; Master''s','Multiple Fields / Eligible programs','','https://www.manchester.ac.uk/study/international/finance-and-funding/scholarships/'),
('Birmingham Global Masters Scholarship','University of Birmingham','United Kingdom','Master''s','Multiple Fields','','https://www.birmingham.ac.uk/study/fees-and-funding/scholarships'),
('Glasgow International Leadership Scholarship','University of Glasgow','United Kingdom','Master''s','Multiple Fields','','https://www.gla.ac.uk/scholarships/'),
('Nottingham Developing Solutions Scholarship','University of Nottingham','United Kingdom','Master''s','Program-specific / Development-related','','https://www.nottingham.ac.uk/studywithus/international-applicants/scholarships-funding/developing-solutions-masters-scholarship.aspx'),
('Durham University Scholarships','Durham University','United Kingdom','Undergraduate; Master''s','Multiple Fields / Program-specific','','https://www.durham.ac.uk/study/scholarships/'),
('St Andrews International Excellence Scholarship','University of St Andrews','United Kingdom','Undergraduate','Multiple Fields','','https://www.st-andrews.ac.uk/study/fees-and-funding/scholarships/'),
('Leiden University Excellence Scholarship','Leiden University','Netherlands','Master''s','Multiple Fields / Eligible programs','','https://www.universiteitleiden.nl/en/education/study-programmes/master/scholarships'),
('Maastricht NL-High Potential Scholarship','Maastricht University','Netherlands','Master''s','Multiple Fields / Eligible programs','','https://www.maastrichtuniversity.nl/education/scholarships'),
('TU Delft Justus & Louise van Effen Scholarship','TU Delft','Netherlands','Master''s','Engineering; Technology; Science; Architecture','','https://www.tudelft.nl/en/education/programmes/masters/msc-scholarships'),
('ETH Zurich Excellence Scholarship','ETH Zurich','Switzerland','Master''s','Multiple Fields','','https://ethz.ch/en/studies/master/financial/scholarships/excellence-scholarship.html'),
('EPFL Excellence Fellowships','EPFL','Switzerland','Master''s','Multiple Fields','','https://www.epfl.ch/education/studies/en/financing-study/scholarships/'),
('UNIL Master''s Grants','University of Lausanne','Switzerland','Master''s','Multiple Fields','','https://www.unil.ch/central/home/menuinst/formation/bourses-et-aides-financieres.html'),
('University of Zurich Scholarships','University of Zurich','Switzerland','Master''s; PhD','Multiple Fields / Program-specific','','https://www.uzh.ch/en/studies/application/scholarships.html'),
('International Talents @Unibo','University of Bologna','Italy','Undergraduate; Master''s','Multiple Fields / Program-specific','','https://www.unibo.it/en/study/fees-and-funding/scholarships-and-subsidies/international-talents-at-unibo'),
('Padua International Excellence Scholarship','University of Padua','Italy','Undergraduate; Master''s','Multiple Fields / English-taught programs','','https://www.unipd.it/en/scholarships'),
('Politecnico di Milano Merit Scholarships','Politecnico di Milano','Italy','Master''s','Engineering; Architecture; Design','','https://www.polimi.it/en/prospective-students/how-to-enrol/laurea-magistrale-equivalent-to-master-of-science/scholarships'),
('Bocconi International Awards','Bocconi University','Italy','Undergraduate; Master''s','Business & Economics; Data/Computer Science; Program-specific','','https://www.unibocconi.it/en/applying-bocconi/fees-and-funding/scholarships'),
('Sciences Po Émile Boutmy Scholarship','Sciences Po','France','Undergraduate; Master''s','Multiple Fields','','https://www.sciencespo.fr/students/en/fees-funding/scholarships/emile-boutmy-scholarship/'),
('HEC Paris Scholarships','HEC Paris','France','Master''s; MBA','Business & Economics','','https://www.hec.edu/en/finance-your-studies'),
('University of Helsinki International Scholarships','University of Helsinki','Finland','Master''s','Multiple Fields','','https://www.helsinki.fi/en/admissions-and-education/apply-bachelors-and-masters-programmes/scholarships-and-tuition-fees'),
('Aalto University Excellence Scholarship','Aalto University','Finland','Master''s','Multiple Fields','','https://www.aalto.fi/en/study-options/aalto-university-scholarship-programme'),
('University of Oulu International Scholarship','University of Oulu','Finland','Master''s','Multiple Fields','','https://www.oulu.fi/en/apply/international-scholarships'),
('University of Copenhagen Danish Government Scholarships','University of Copenhagen / Danish Government','Denmark','Master''s','Multiple Fields / Selected programs','','https://studies.ku.dk/masters/tuition-fees-and-funding/scholarships/'),
('Aarhus University Danish State Scholarships','Aarhus University / Danish Government','Denmark','Master''s','Multiple Fields / Selected programs','','https://international.au.dk/education/admissions/tuition-fees-and-scholarships'),
('Lund University Global Scholarship','Lund University','Sweden','Master''s; selected Bachelor''s','Multiple Fields','','https://www.lunduniversity.lu.se/node/83'),
('KTH Scholarship','KTH Royal Institute of Technology','Sweden','Master''s','Engineering; ICT; Science; Architecture','','https://www.kth.se/en/studies/master/scholarships/kth-scholarship-1.792056'),
('Chalmers IPOET Scholarship','Chalmers University of Technology','Sweden','Master''s','Engineering; Technology; Science','','https://www.chalmers.se/en/education/fees-finance-and-scholarships/scholarships/'),
('Uppsala University Global Scholarships','Uppsala University','Sweden','Master''s','Multiple Fields','','https://www.uu.se/en/study/scholarships'),
('Macquarie University Vice-Chancellor''s Scholarship','Macquarie University','Australia','Undergraduate; Master''s','Multiple Fields','','https://www.mq.edu.au/study/admissions-and-entry/scholarships'),
('University of Sydney International Scholarships','University of Sydney','Australia','Master''s; PhD; Undergraduate','Multiple Fields / Research','','https://www.sydney.edu.au/scholarships/'),
('Monash International Leadership Scholarship','Monash University','Australia','Undergraduate','Multiple Fields','','https://www.monash.edu/study/fees-scholarships/scholarships'),
('University of Melbourne Graduate Research Scholarships','University of Melbourne','Australia','Master''s; PhD','Multiple Fields / Research','','https://scholarships.unimelb.edu.au/awards/graduate-research-scholarships'),
('ANU Chancellor''s International Scholarship','Australian National University','Australia','Undergraduate; Master''s','Multiple Fields','','https://study.anu.edu.au/scholarships'),
('University of Queensland Scholarships','University of Queensland','Australia','Undergraduate; Master''s; PhD','Multiple Fields','','https://scholarships.uq.edu.au/'),
('University of Auckland International Student Excellence Scholarship','University of Auckland','New Zealand','Undergraduate; Master''s','Multiple Fields','','https://www.auckland.ac.nz/en/study/scholarships-and-awards.html'),
('University of Waikato International Excellence Scholarship','University of Waikato','New Zealand','Undergraduate; Master''s','Multiple Fields','','https://www.waikato.ac.nz/study/scholarships'),
('Victoria University of Wellington Tongarewa Scholarship','Victoria University of Wellington','New Zealand','Undergraduate; Master''s','Multiple Fields','','https://www.wgtn.ac.nz/scholarships'),
('University of Otago International Scholarships','University of Otago','New Zealand','Undergraduate; Master''s; Research','Multiple Fields / Research','','https://www.otago.ac.nz/study/scholarships'),
('University of Canterbury International Scholarships','University of Canterbury','New Zealand','Undergraduate; Master''s','Multiple Fields','','https://www.canterbury.ac.nz/study/getting-started/scholarships'),
('University of Waterloo International Scholarships','University of Waterloo','Canada','Undergraduate','Multiple Fields','','https://uwaterloo.ca/future-students/financing/scholarships'),
('University of Alberta International Scholarships','University of Alberta','Canada','Undergraduate; Graduate','Multiple Fields','','https://www.ualberta.ca/en/admissions/international/admission/scholarships.html'),
('McGill Scholarships and Aid','McGill University','Canada','Undergraduate; Master''s; PhD','Multiple Fields','','https://www.mcgill.ca/studentaid/scholarships-aid'),
('University of Toronto Ontario Graduate Scholarship','University of Toronto / Ontario','Canada','Master''s; PhD','Multiple Fields','','https://www.sgs.utoronto.ca/awards/ontario-graduate-scholarship/'),
('University of Toronto Connaught International Scholarship','University of Toronto','Canada','PhD','Multiple Fields','','https://www.sgs.utoronto.ca/awards/'),
('University of Calgary International Entrance Scholarship','University of Calgary','Canada','Undergraduate','Multiple Fields','','https://ucalgary.ca/registrar/finances/awards-scholarships'),
('University of Ottawa International Scholarships','University of Ottawa','Canada','Undergraduate; Master''s','Multiple Fields','','https://www.uottawa.ca/study/fees-financial-support/scholarships'),
('Australian Government Research Training Program (RTP)','Australian Government','Australia','Master''s; PhD','Multiple Fields / Research','','https://www.education.gov.au/research-training-program'),
('University of Sydney RTP Scholarship','University of Sydney / Australian Government','Australia','Master''s; PhD','Multiple Fields / Research','','https://www.sydney.edu.au/scholarships/'),
('Monash Graduate Scholarship','Monash University','Australia','Master''s; PhD','Multiple Fields / Research','','https://www.monash.edu/graduate-research/future-students/scholarships'),
('UQ Graduate School Scholarships','University of Queensland','Australia','Master''s; PhD','Multiple Fields / Research','','https://graduate-school.uq.edu.au/scholarships'),
('ANU RTP Scholarship','Australian National University / Australian Government','Australia','Master''s; PhD','Multiple Fields / Research','','https://study.anu.edu.au/scholarships'),
('Oxford-Weidenfeld and Hoffmann Scholarships','University of Oxford / Weidenfeld-Hoffmann Trust','United Kingdom','Master''s','Multiple Fields / Eligible Oxford programs','','https://www.ox.ac.uk/admissions/graduate/fees-and-funding/graduate-scholarships/weidenfeld-and-hoffmann-scholarships'),
('Oxford Reach Scholarship','University of Oxford','United Kingdom','Undergraduate','Multiple Fields / Eligible courses','','https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford-scholarship')
ON DUPLICATE KEY UPDATE title=VALUES(title);

INSERT INTO universities(name,country,city,description,official_url) VALUES
('University of Oxford','United Kingdom','Oxford','Research-intensive university.','https://www.ox.ac.uk/'),
('University of Cambridge','United Kingdom','Cambridge','Research-intensive university.','https://www.cam.ac.uk/'),
('Imperial College London','United Kingdom','London','Science, engineering, medicine and business.','https://www.imperial.ac.uk/'),
('University College London','United Kingdom','London','Multidisciplinary research university.','https://www.ucl.ac.uk/'),
('Stanford University','United States','Stanford','Research university in California.','https://www.stanford.edu/'),
('Harvard University','United States','Cambridge','Research university with broad disciplines.','https://www.harvard.edu/'),
('MIT','United States','Cambridge','Science, engineering and technology focused research university.','https://www.mit.edu/'),
('University of Toronto','Canada','Toronto','Large public research university.','https://www.utoronto.ca/'),
('University of British Columbia','Canada','Vancouver','Public research university.','https://www.ubc.ca/'),
('McGill University','Canada','Montreal','Public research university.','https://www.mcgill.ca/'),
('University of Melbourne','Australia','Melbourne','Public research university.','https://www.unimelb.edu.au/'),
('University of Sydney','Australia','Sydney','Public research university.','https://www.sydney.edu.au/'),
('University of Tokyo','Japan','Tokyo','Leading Japanese research university.','https://www.u-tokyo.ac.jp/en/'),
('Kyoto University','Japan','Kyoto','Major Japanese research university.','https://www.kyoto-u.ac.jp/en'),
('Seoul National University','South Korea','Seoul','National research university.','https://en.snu.ac.kr/'),
('ETH Zurich','Switzerland','Zurich','Science and technology research university.','https://ethz.ch/en.html'),
('TU Delft','Netherlands','Delft','Engineering and technology university.','https://www.tudelft.nl/en/'),
('Technical University of Munich','Germany','Munich','Technical research university.','https://www.tum.de/en/'),
('University of Amsterdam','Netherlands','Amsterdam','Comprehensive research university.','https://www.uva.nl/en'),
('Peking University','China','Beijing','Comprehensive research university.','https://english.pku.edu.cn/');

INSERT INTO fields(name,description) VALUES
('Computer Science','Programming, software, AI and computing systems.'),
('Information Technology','Computing infrastructure, applications and digital services.'),
('Information and Communication Technology','Communication systems, software and digital technologies.'),
('Artificial Intelligence','Machine learning, intelligent systems and AI applications.'),
('Data Science','Statistics, data analysis and machine learning.'),
('Bioinformatics','Computing methods for biological and biomedical data.'),
('Biotechnology','Biological technology and applied life sciences.'),
('Biomedical Engineering','Engineering approaches to medicine and healthcare.'),
('Electrical Engineering','Electronics, power, control and electrical systems.'),
('Electronics and Communication','Electronics, telecommunications and communication systems.'),
('Mechanical Engineering','Machines, manufacturing and mechanical systems.'),
('Civil Engineering','Infrastructure, construction and environmental systems.'),
('Business Administration','Management, entrepreneurship and business.'),
('Economics','Economic theory, policy and quantitative analysis.'),
('Public Health','Population health and healthcare systems.'),
('Environmental Science','Environment, climate and sustainability.'),
('Physics','Fundamental and applied physical sciences.'),
('Chemistry','Chemical science and laboratory research.'),
('Mathematics','Pure and applied mathematical sciences.'),
('Social Sciences','Society, policy, development and human behaviour.')
ON DUPLICATE KEY UPDATE description=VALUES(description);
